name: pawlly
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.6+28

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  

  #firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3

  nb_utils: ^7.0.5
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  stream_transform: ^2.1.0
  uuid: ^4.5.1

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  permission_handler: ^12.0.0+1

  # State Management
  get: ^4.6.6

  # Notification

  # Payment
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.3.7
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  pay: ^3.2.1
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.3.0
  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery

  photo_view: ^0.15.0

  #intent
  android_intent_plus: ^5.2.0

  datepicker_dropdown: ^0.1.5
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  country_picker: ^2.0.26

  # MAP
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  #SHIMMER
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  lottie: ^3.1.3
  flutter_html: ^3.0.0-beta.2
  phonepe_payment_sdk: ^3.0.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/images/walkthrough_images/
    - assets/images/dog_paw/
    - assets/images/pet_profile/
    - assets/images/sitter/
    - assets/images/notification/
    - assets/images/shop/
    - assets/images/choosepet/
    - assets/icons/profile_icons/
    - assets/icons/service_icons/
    - assets/icons/navigation/
    - assets/icons/upi_payment/
    - assets/images/brand/
    - assets/lottie/
    - assets/images/auth_images/



